Repository thoth-station/python, pull requests merged in 2018-12, with the labels that each got.

#27 Adjust report messages so that they are more generic
  thoth/python/project.py
Labels: size/XS

#26 Use index url in reports rather than index name
  thoth/python/digests_fetcher.py
  thoth/python/project.py
Labels: approved, size/S

#29 Release of version 0.4.0
  CHANGELOG.md
  thoth/python/__init__.py
Labels: bot, size/S

#31 Introduce to_tuple method
  thoth/python/package_version.py
Labels: size/XS

#30 Automatic update of dependency pytest from 4.0.1 to 4.0.2
  Pipfile.lock
Labels: bot

#32 Make linter happy again
  thoth/python/pipfile.py
Labels: size/XS

#37 Release of version 0.4.3
  CHANGELOG.md
  thoth/python/__init__.py
Labels: bot, size/XS

#38 Test creation of project from package versions
  Pipfile
  Pipfile.lock
  tests/test_pipfile.py
  thoth/python/exceptions.py
  thoth/python/pipfile.py
  thoth/python/project.py
Labels: size/L

#40 Create static method for semver parsing
  thoth/python/package_version.py
Labels: size/S

#39 Add testsuite for provenance checks
  tests/test_provenance.py
  thoth/python/project.py
Labels: size/L
