Repository thoth-station/python, pull requests merged in 2019-11, with the labels that each got.

#161 Normalize link text for comparison to package name
  thoth/python/source.py
Labels: approved, size/XS

#160 Feature: async source
  .coafile
  .gitignore
  Pipfile
  Pipfile.lock
  docs/source/conf.py
  pyproject.toml
  setup.py
  tests/test_aiosource.py
  thoth/python/__init__.py
  thoth/python/aiosource.py
Labels: approved, size/XL

#162 Introduce a method for checking if the given package is provided by index
  thoth/python/source.py
Labels: approved, size/S

#163 Normalize package name before checking its availability
  thoth/python/source.py
Labels: approved, size/XS

#157 Use packaging module to be fully compliant with Python ecosystem
  Pipfile
  Pipfile.lock
  tests/test_package_version.py
  tests/test_project.py
  thoth/python/package_version.py
  thoth/python/source.py
Labels: size/L, size/M

#164 Add missing aiohttp dependency
  requirements.txt
Labels: approved, size/XS

#165 Fix metadata propagation when instantiating PipfileLock
  thoth/python/pipfile.py
Labels: approved, size/XS

#167 Release of version 0.7.1
  CHANGELOG.md
  thoth/python/__init__.py
Labels: bot, size/L, size/S

#168 Remove setuptools from Pipenv
  Pipfile
  Pipfile.lock
Labels: approved, size/XS

#171 Automatic update of dependency thoth-common from 0.9.14 to 0.9.15
  Pipfile.lock
Labels: bot

#172 Automatic update of dependency thoth-common from 0.9.15 to 0.9.16
  Pipfile.lock
Labels: bot, size/S

#173 Automatic update of dependency pytest from 5.2.2 to 5.2.3
  Pipfile.lock
Labels: bot, size/XS

#174 Automatic update of dependency pytest from 5.2.3 to 5.2.4
  Pipfile.lock
Labels: bot, size/XS

#175 Automatic update of dependency pytest from 5.2.4 to 5.3.0
  Pipfile.lock
Labels: bot, size/S

#176 Automatic update of dependency lxml from 4.4.1 to 4.4.2
  Pipfile.lock
Labels: bot, size/L

#177 Automatic update of dependency pytest from 5.3.0 to 5.3.1
  Pipfile.lock
Labels: bot, size/XS

#178 Automatic update of dependency thoth-common from 0.9.16 to 0.9.17
  Pipfile.lock
Labels: bot, size/L

#179 Automatic update of dependency thoth-analyzer from 0.1.4 to 0.1.5
  Pipfile.lock
Labels: bot, size/M

#180 Automatic update of dependency thoth-common from 0.9.17 to 0.9.18
  Pipfile.lock
Labels: bot, size/M

#181 Automatic update of dependency thoth-common from 0.9.18 to 0.9.19
  Pipfile.lock
Labels: bot, size/XS
