Repository thoth-station/python, pull requests merged in 2019-09, with the labels that each got.

#129 Automatic update of dependency semantic-version from 2.8.1 to 2.8.2
  Pipfile.lock
Labels: bot

#130 Fix Typo
  thoth/python/artifact.py
Labels: approved, size/XS

#131 fix symbols
  thoth/python/artifact.py
Labels: approved, size/XS

#132 Fix incosistent runtime environment attribute instantiation
  thoth/python/project.py
Labels: approved, size/S

#134 Move testcase to its proper location
  tests/test_project.py
  thoth/python/project.py
Labels: approved, size/M

#135 Release of version 0.6.2
  CHANGELOG.md
  thoth/python/__init__.py
Labels: bot, size/M

#136 Automatic update of dependency thoth-common from 0.9.8 to 0.9.9
  Pipfile.lock
Labels: bot

#137 Automatic update of dependency thoth-common from 0.9.9 to 0.9.10
  Pipfile.lock
Labels: bot

#138 Automatic update of dependency packaging from 19.1 to 19.2
  Pipfile.lock
Labels: bot

#139 Normalize Python package versions according to PEP-440
  Pipfile
  Pipfile.lock
  requirements.txt
  tests/test_package_version.py
  thoth/python/package_version.py
Labels: approved, size/M

#141 Release of version 0.6.3
  CHANGELOG.md
  thoth/python/__init__.py
Labels: bot, size/XS

#144 Use packaging for package name normalization
  thoth/python/package_version.py
Labels: approved, size/XS
