Repository thoth-station/python, pull requests merged in 2019-08, with the labels that each got.

#106 Automatic update of dependency thoth-common from 0.9.5 to 0.9.6
  Pipfile.lock
Labels: bot

#109 Automatic update of dependency lxml from 4.4.0 to 4.4.1
  Pipfile.lock
Labels: bot

#110 Normalize Python package names according to PEP-0503
  tests/data/pipfiles/Pipfile_test1.lock
  tests/test_package_version.py
  thoth/python/package_version.py
Labels: size/M

#107 Add missing runtime environment in dict reports of project
  thoth/python/project.py
Labels: size/XS

#112 Release of version 0.6.1
  CHANGELOG.md
  thoth/python/__init__.py
Labels: bot, size/S

#113 Automatic update of dependency thoth-common from 0.9.6 to 0.9.7
  Pipfile.lock
Labels: bot

#114 Automatic update of dependency thoth-common from 0.9.7 to 0.9.8
  Pipfile.lock
Labels: bot

#116 Remove unused imports
  thoth/python/artifact.py
  thoth/python/source.py
Labels: approved, size/S

#117 Automatic update of dependency pytest from 5.0.1 to 5.1.0
  Pipfile.lock
Labels: bot

#119 Add missing requirements
  requirements.txt
Labels: approved, size/XS

#122 Fix temporary name assignment
  thoth/python/artifact.py
Labels: approved, size/XS

#123 Automatic update of dependency pytest from 5.1.0 to 5.1.1
  Pipfile.lock
Labels: bot

#124 Automatic update of dependency semantic-version from 2.6.0 to 2.7.0
  Pipfile.lock
Labels: bot

#125 Automatic update of dependency semantic-version from 2.7.0 to 2.7.1
  Pipfile.lock
Labels: bot

#126 Automatic update of dependency semantic-version from 2.7.1 to 2.8.0
  Pipfile.lock
Labels: bot

#127 Automatic update of dependency semantic-version from 2.8.0 to 2.8.1
  Pipfile.lock
Labels: bot

#128 Automatic update of dependency pytest from 5.1.1 to 5.1.2
  Pipfile.lock
Labels: bot
