Repository thoth-station/python, pull requests merged in 2019-03, with the labels that each got.

#52 Fixes, reformat and include runtime env in project abstraction
  thoth/python/__init__.py
  thoth/python/configuration.py
  thoth/python/helpers.py
  thoth/python/package_version.py
  thoth/python/packages.py
  thoth/python/pipfile.py
  thoth/python/project.py
  thoth/python/source.py
Labels: approved, size/XL

#53 Introduce configuration check method
  thoth/python/project.py
Labels: size/M

#55 added pytest jobs to all the pipes
  .coafile
  .zuul.yaml
Labels: approved, size/S, size/XS

#56 Minor fixes in implementation
  thoth/python/pipfile.py
  thoth/python/project.py
Labels: size/M

#54 Requires are optional field in Pipfile
  thoth/python/project.py
Labels: size/M, size/XS

#57 Provide runtime environment parameter
  .coafile
  thoth/python/helpers.py
  thoth/python/package_version.py
  thoth/python/project.py
  thoth/python/source.py
Labels: size/M, size/S

#58 Use Sphinx for generating documentation
  .coafile
  .gitignore
  README.rst
  docs/source/conf.py
  docs/source/index.rst
  setup.py
Labels: size/L, size/XL

#62 Add Thoth's configuration file
  .thoth.yaml
  Pipfile
  Pipfile.lock
Labels: size/L, size/S

#64 Release of version 0.5.0
  CHANGELOG.md
  thoth/python/__init__.py
Labels: bot, size/M

#65 Propagate package name to debug message
  thoth/python/package_version.py
Labels: size/S

#67 Automatic update of dependency lxml from 4.3.2 to 4.3.3
  Pipfile.lock
Labels: bot

#66 Automatic update of dependency flexmock from 0.10.3 to 0.10.4
  Pipfile.lock
Labels: bot

#68 Automatic update of dependency pytest from 4.3.1 to 4.4.0
  Pipfile.lock
Labels: bot
