Repository thoth-station/python, pull requests merged in 2019-10, with the labels that each got.

#145 Do not rely on pkg_resources, use packaging for version parsing
  Pipfile.lock
  thoth/python/package_version.py
Labels: approved, size/M

#147 Substitute contoml with toml
  Pipfile
  Pipfile.lock
  requirements.txt
  tests/test_pipfile.py
  thoth/python/pipfile.py
Labels: approved, size/M

#149 Release of version 0.6.4
  CHANGELOG.md
  thoth/python/__init__.py
Labels: bot, human_intervention_required, size/XS

#150 Add support for parsing extras from Pipfile and Pipfile.lock
  tests/data/pipfiles/Pipfile_extras
  tests/data/pipfiles/Pipfile_extras.lock
  tests/test_pipfile.py
  thoth/python/package_version.py
Labels: approved, size/L

#151 Fix handling of user arguments when running pytest from setup.py
  setup.py
Labels: approved, size/S

#153 Release of version 0.6.5
  CHANGELOG.md
  thoth/python/__init__.py
Labels: bot, size/XS

#155 Start using mypy for type checking
  .gitignore
  Pipfile
  Pipfile.lock
  setup.py
  tests/base.py
  tests/test_package_version.py
  tests/test_pipfile.py
  tests/test_project.py
  tests/test_provenance.py
  tests/test_source.py
Labels: approved, size/L

#154 Drop version specification
  tests/test_package_version.py
  thoth/python/package_version.py
Labels: approved, size/S

#156 Provide a way to define runtime environment when instantiating from package versions
  thoth/python/project.py
Labels: approved, size/XS
