Repository thoth-station/python, pull requests merged in 2019-07, with the labels that each got.

#91 Automatic update of dependency pytest from 5.0.0 to 5.0.1
  Pipfile.lock
Labels: bot

#93 Automatic update of dependency thoth-common from 0.9.1 to 0.9.2
  Pipfile.lock
Labels: bot

#94 Automatic update of dependency thoth-common from 0.9.2 to 0.9.3
  Pipfile.lock
Labels: bot

#89 testing get_package_hashes() with_included_files
  tests/data/tensorflow_serving_api-1.13.0-py2.py3-none-any.json
  tests/data/tensorflow_serving_api-1.13.0-py2.py3-none-any.whl
  tests/test_source.py
  thoth/python/source.py
Labels: approved, do-not-merge/work-in-progress, size/L, size/XXL

#95 Automatic update of dependency thoth-common from 0.9.3 to 0.9.4
  Pipfile.lock
Labels: bot

#96 extracting tar.gz files
  thoth/python/source.py
Labels: approved, do-not-merge/work-in-progress, size/S

#98 Release of version 0.6.0
  CHANGELOG.md
  thoth/python/__init__.py
Labels: bot, size/M

#99 Automatic update of dependency thoth-common from 0.9.4 to 0.9.5
  Pipfile.lock
Labels: bot

#100 Output filepath and sha256 for all files inside artifact
  tests/data/tensorflow_serving_api-1.13.0-py2.py3-none-any.json
  tests/test_source.py
  thoth/python/source.py
Labels: approved, size/L, size/M, work-in-progress

#103 Automatic update of dependency lxml from 4.3.4 to 4.3.5
  Pipfile.lock
Labels: bot

#105 Automatic update of dependency lxml from 4.3.5 to 4.4.0
  Pipfile.lock
Labels: bot
