Repository thoth-station/python, pull requests merged in 2019-01, with the labels that each got.

#42 Make sure we use warehouse API only if it is available
  thoth/python/__init__.py
  thoth/python/source.py
Labels: size/XS

#44 Release of version 0.4.5
  CHANGELOG.md
  thoth/python/__init__.py
Labels: bot, size/M

#45 Avoid issues with bs4 when parsing simple API package listing
  Pipfile
  Pipfile.lock
  requirements.txt
Labels: approved, size/M

#46 Improve packages gathering from indexes
  thoth/python/source.py
Labels: size/S

#47 Fix typo
  thoth/python/pipfile.py
Labels: size/XS

#49 Remove unused imports
  thoth/python/project.py
Labels: size/XS

#48 Update .gitignore
  .gitignore
Labels: size/XS
