Repository thoth-station/python, pull requests merged in 2019-12, with the labels that each got.

#183 Change Sphinx theme
  .coafile
  docs/source/conf.py
Labels: size/S

#184 Automatic update of dependency thoth-common from 0.9.19 to 0.9.21
  Pipfile.lock
Labels: bot, size/L

#186 Automatic update of dependency thoth-analyzer from 0.1.5 to 0.1.6
  Pipfile.lock
Labels: bot, size/L

#185 Automatic update of dependency pyelftools from 0.25 to 0.26
  Pipfile.lock
Labels: bot, size/L

#187 Add Google Analytics
  docs/source/_templates/layout.html
Labels: approved, size/S

#189 Point documentation to other libraries
  docs/source/index.rst
Labels: approved, size/XS

#190 Automatic update of dependency thoth-analyzer from 0.1.6 to 0.1.7
  Pipfile.lock
Labels: bot, size/S

#191 Automatic update of dependency thoth-common from 0.9.21 to 0.9.22
  Pipfile.lock
Labels: bot, size/M

#192 Automatic update of dependency pytest from 5.3.1 to 5.3.2
  Pipfile.lock
Labels: bot, size/XS
