Repository thoth-station/python, pull requests merged in 2020-07, with the labels that each got.

#287 add more functions to aiosource
  thoth/python/aiosource.py
Labels: approved, size/M

#288 Automatic update of dependency thoth-common from 0.13.13 to 0.14.2
  Pipfile.lock
Labels: approved, bot, size/M

#290 Automatic update of dependency pytest-timeout from 1.4.1 to 1.4.2
  Pipfile.lock
Labels: approved, bot, size/XS

#289 Automatic update of dependency lxml from 4.5.1 to 4.5.2
  Pipfile.lock
Labels: approved, bot, size/M

#286 Replace legacy urls
  Pipfile.lock
  requirements.txt
  tests/data/pipfiles/Pipfile_requirements
  tests/data/pipfiles/Pipfile_requirements.lock
  tests/data/pipfiles/Pipfile_test1
  tests/data/pipfiles/Pipfile_test1.lock
  tests/test_pipfile.py
  thoth/python/aiosource.py
  thoth/python/source.py
Labels: approved, size/XXL

#295 Automatic update of dependency thoth-common from 0.14.2 to 0.16.0
  Pipfile.lock
Labels: approved, bot, size/L
