Repository thoth-station/python, pull requests merged in 2020-10, with the labels that each got.

#314 make pre-commit happy
  .pre-commit-config.yaml
  MANIFEST.in
  docs/source/conf.py
  setup.py
  tests/base.py
  tests/data/selinon-warehouse-api.json
  tests/data/tensorflow.html
  tests/data/tensorflow_serving_api-1.13.0-py2.py3-f29-any.json
  tests/test_aiosource.py
  tests/test_helpers.py
  tests/test_package_version.py
  tests/test_pipfile.py
  tests/test_project.py
  tests/test_provenance.py
  tests/test_source.py
  thoth/python/__init__.py
  thoth/python/aiosource.py
  thoth/python/artifact.py
  thoth/python/configuration.py
  thoth/python/helpers.py
  thoth/python/package_version.py
  thoth/python/pipfile.py
  thoth/python/project.py
  thoth/python/source.py
Labels: approved, size/XXL

#319 Automatic update of dependency pytest from 6.0.2 to 6.1.2
  Pipfile.lock
Labels: approved, bot, size/L

#315 Automatic update of dependency thoth-common from 0.20.0 to 0.20.2
  Pipfile.lock
Labels: approved, bot, size/XS

#316 Automatic update of dependency lxml from 4.5.2 to 4.6.1
  Pipfile.lock
Labels: approved, bot, size/M

#317 Automatic update of dependency pyelftools from 0.26 to 0.27
  Pipfile.lock
Labels: approved, bot, size/XS

#318 Automatic update of dependency aiohttp from 3.6.2 to 3.7.2
  Pipfile.lock
Labels: approved, bot, size/M
