Repository thoth-station/python, pull requests merged in 2020-12, with the labels that each got.

#322 bump python version
  .aicoe-ci.yaml
  .thoth.yaml
  Pipfile
  Pipfile.lock
Labels: approved, size/L

#326 Relock to fix typing extension marker issue
  Pipfile.lock
Labels: approved, size/S

#329 Add missing GitHub templates
  .github/CODEOWNERS
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved, size/S

#325 Adjust how source name is derived
  tests/test_helpers.py
  tests/test_project.py
  thoth/python/source.py
Labels: approved, size/S

#328 Fix testsuite for Python 3.8
  thoth/python/aiosource.py
Labels: approved, size/XS
