Repository thoth-station/python, pull requests merged in 2020-02, with the labels that each got.

#230 Automatic update of dependency thoth-common from 0.10.1 to 0.10.2
  Pipfile.lock
Labels: bot, size/XS

#231 Automatic update of dependency thoth-common from 0.10.2 to 0.10.3
  Pipfile.lock
Labels: bot, size/S

#232 Automatic update of dependency thoth-common from 0.10.3 to 0.10.4
  Pipfile.lock
Labels: bot, size/XS

#233 Automatic update of dependency thoth-common from 0.10.4 to 0.10.5
  Pipfile.lock
Labels: bot, size/S

#234 Update .thoth.yaml
  .thoth.yaml
Labels: approved, size/S

#235 Add templates for releases
  .github/ISSUE_TEMPLATE/major-release.md
  .github/ISSUE_TEMPLATE/minor-release.md
  .github/ISSUE_TEMPLATE/patch-release.md
Labels: approved, size/M

#236 Automatic update of dependency thoth-common from 0.10.5 to 0.10.6
  Pipfile.lock
Labels: bot, size/S

#237 Automatic update of dependency thoth-common from 0.10.6 to 0.10.7
  Pipfile.lock
Labels: bot, size/S

#238 When checking if version exists when querying the DB the same package…
  thoth/python/aiosource.py
Labels: approved, size/XS

#239 Automatic update of dependency requests from 2.22.0 to 2.23.0
  Pipfile.lock
Labels: bot, size/S

#240 Automatic update of dependency pytest-mypy from 0.4.2 to 0.5.0
  Pipfile.lock
Labels: bot, size/M

#241 Automatic update of dependency thoth-common from 0.10.7 to 0.10.8
  Pipfile.lock
Labels: bot, size/XS

#242 Automatic update of dependency thoth-common from 0.10.8 to 0.10.9
  Pipfile.lock
Labels: bot, size/S
