Repository thoth-station/python, pull requests merged in 2020-01, with the labels that each got.

#195 Automatic update of dependency packaging from 19.2 to 20.0
  Pipfile.lock
Labels: bot, size/L

#196 Automatic update of dependency pytest-timeout from 1.3.3 to 1.3.4
  Pipfile.lock
Labels: bot, size/M

#198 Run the testsuite
  .zuul.yaml
Labels: size/XS

#197 Add pip/pip-tools support
  tests/data/pipfiles/Pipfile_requirements
  tests/data/pipfiles/Pipfile_requirements.lock
  tests/test_pipfile.py
  thoth/python/package_version.py
  thoth/python/pipfile.py
  thoth/python/project.py
Labels: approved, size/L

#200 Release of version 0.8.0
  CHANGELOG.md
  thoth/python/__init__.py
Labels: bot, size/L

#194 Happy new year!
  docs/source/conf.py
  tests/__init__.py
  tests/base.py
  tests/test_aiosource.py
  tests/test_package_version.py
  tests/test_pipfile.py
  tests/test_project.py
  tests/test_provenance.py
  tests/test_source.py
  thoth/python/__init__.py
  thoth/python/aiosource.py
  thoth/python/artifact.py
  thoth/python/configuration.py
  thoth/python/digests_fetcher.py
  thoth/python/exceptions.py
  thoth/python/helpers.py
  thoth/python/package_version.py
  thoth/python/packages.py
  thoth/python/pipfile.py
  thoth/python/project.py
  thoth/python/source.py
Labels: approved, size/M

#201 Pass pip allows one --index-url per run
  tests/test_pipfile.py
  thoth/python/pipfile.py
Labels: approved, size/S

#202 Automatic update of dependency thoth-common from 0.9.22 to 0.9.23
  Pipfile.lock
Labels: bot, size/XS

#203 Move package parsing logic from thoth-solver
  tests/data/requirements/example_dir1/requirements.txt
  tests/data/requirements/example_dir2/requirements.in
  tests/data/requirements/example_dir2/requirements.txt
  tests/data/requirements/example_dir3/requirements.in
  tests/data/requirements/parse_requirements.txt
  tests/data/requirements/parse_requirements_empty.txt
  tests/test_helpers.py
  tests/test_project.py
  thoth/python/helpers.py
  thoth/python/pipfile.py
  thoth/python/project.py
Labels: approved, size/XL

#206 Release of version 0.9.0
  CHANGELOG.md
  thoth/python/__init__.py
Labels: bot, size/XS

#207 Fix sources dict handling
  thoth/python/project.py
Labels: approved, size/XS

#209 Release of version 0.9.1
  CHANGELOG.md
  thoth/python/__init__.py
Labels: bot, size/XS

#210 Automatic update of dependency thoth-common from 0.9.23 to 0.9.24
  Pipfile.lock
Labels: bot, size/S

#211 Automatic update of dependency thoth-common from 0.9.24 to 0.9.25
  Pipfile.lock
Labels: bot, size/L

#212 Automatic update of dependency thoth-common from 0.9.25 to 0.9.26
  Pipfile.lock
Labels: bot, size/M

#213 Automatic update of dependency thoth-analyzer from 0.1.7 to 0.1.8
  Pipfile.lock
Labels: bot, size/M

#214 Automatic update of dependency thoth-common from 0.9.26 to 0.9.27
  Pipfile.lock
Labels: bot, size/XS

#215 Automatic update of dependency thoth-common from 0.9.27 to 0.9.28
  Pipfile.lock
Labels: bot, size/XS

#216 Automatic update of dependency pytest from 5.3.2 to 5.3.3
  Pipfile.lock
Labels: bot, size/XS

#217 Automatic update of dependency thoth-common from 0.9.28 to 0.9.29
  Pipfile.lock
Labels: bot, size/S

#218 Automatic update of dependency pytest from 5.3.3 to 5.3.4
  Pipfile.lock
Labels: bot, size/S

#220 Automatic update of dependency packaging from 20.0 to 20.1
  Pipfile.lock
Labels: bot, size/M

#221 Automatic update of dependency thoth-common from 0.9.29 to 0.9.30
  Pipfile.lock
Labels: bot, size/S

#222 Automatic update of dependency thoth-common from 0.9.30 to 0.9.31
  Pipfile.lock
Labels: bot, size/XS

#224 Automatic update of dependency thoth-common from 0.9.31 to 0.10.0
  Pipfile.lock
Labels: bot, size/S

#225 Automatic update of dependency lxml from 4.4.2 to 4.4.3
  Pipfile.lock
Labels: bot, size/M

#223 Fix if version is prefix to another version
  tests/test_source.py
  thoth/python/source.py
Labels: approved, size/M

#228 Automatic update of dependency pytest from 5.3.4 to 5.3.5
  Pipfile.lock
Labels: bot, size/XS

#227 Add change to the other TODO
  thoth/python/source.py
Labels: approved, size/S

#229 Automatic update of dependency thoth-common from 0.10.0 to 0.10.1
  Pipfile.lock
Labels: bot, size/S
