Repository thoth-station/python, pull requests merged in 2020-08, with the labels that each got.

#293 Feature/ordered versions
  thoth/python/source.py
Labels: approved, size/S

#298 Automatic update of dependency pytest from 5.4.3 to 6.0.1
  Pipfile.lock
Labels: approved, bot, size/M

#299 Adjust docstring
  thoth/python/source.py
Labels: approved, size/XS

#303 Release of version 0.10.1
  CHANGELOG.md
  thoth/python/__init__.py
Labels: approved, bot, size/S

#304 Add maintainers
  .thoth.yaml
Labels: approved, size/XS

#305 fix package-version equality
  thoth/python/package_version.py
Labels: approved, size/XS

#306 Automatic update of dependency pytest-cov from 2.10.0 to 2.10.1
  Pipfile.lock
Labels: approved, bot, size/S
