Repository thoth-station/python, pull requests merged in 2020-04, with the labels that each got.

#245 Remove typeshed from requirements
  Pipfile
  Pipfile.lock
Labels: size/L

#247 Automatic update of dependency pytest-mypy from 0.6.0 to 0.6.1
  Pipfile.lock
Labels: bot, size/M

#248 Automatic update of dependency thoth-common from 0.12.6 to 0.12.7
  Pipfile.lock
Labels: bot, size/S

#246 Use RHEL 8
  .thoth.yaml
Labels: approved, size/XS

#249 Automatic update of dependency thoth-common from 0.12.7 to 0.12.8
  Pipfile.lock
Labels: bot, size/S

#250 Automatic update of dependency thoth-common from 0.12.8 to 0.12.9
  Pipfile.lock
Labels: bot, size/XS

#252 Raise an exception if a file failed to load
  tests/test_project.py
  thoth/python/exceptions.py
  thoth/python/helpers.py
  thoth/python/project.py
Labels: approved, do-not-merge/needs-rebase, size/M

#254 Release of version 0.9.2
  CHANGELOG.md
  thoth/python/__init__.py
Labels: bot, size/M

#255 Be explicit about errors
  thoth/python/artifact.py
Labels: approved, size/S

#256 Automatic update of dependency pytest-asyncio from 0.10.0 to 0.11.0
  Pipfile.lock
Labels: bot, size/M

#257 Automatic update of dependency thoth-common from 0.12.9 to 0.12.10
  Pipfile.lock
Labels: bot, size/S

#258 Automatic update of dependency thoth-common from 0.12.10 to 0.13.0
  Pipfile.lock
Labels: bot, size/XS

#259 Automatic update of dependency pytest-mypy from 0.6.1 to 0.6.2
  Pipfile.lock
Labels: bot, size/XS

#261 Automatic update of dependency thoth-common from 0.13.0 to 0.13.1
  Pipfile.lock
Labels: bot, size/XS

#260 Automatic update of dependency click from 7.1.1 to 7.1.2
  Pipfile.lock
Labels: bot, size/XS

#262 Automatic update of dependency thoth-common from 0.13.1 to 0.13.2
  Pipfile.lock
Labels: bot
