Repository thoth-station/python, pull requests merged in 2020-06, with the labels that each got.

#267 Cache properties of PackageVersion
  Pipfile.lock
  thoth/python/package_version.py
Labels: approved, size/L

#270 Get release time
  thoth/python/source.py
Labels: approved, size/S

#273 Automatic update of dependency pytest-cov from 2.9.0 to 2.10.0
  Pipfile.lock
Labels: bot, size/M

#275 Release of version 0.10.0
  CHANGELOG.md
  thoth/python/__init__.py
Labels: bot, size/S

#272 Automatic update of dependency pytest-timeout from 1.3.4 to 1.4.1
  Pipfile.lock
Labels: bot, size/XS

#281 Increase pytest timeout
  setup.py
Labels: approved

#283 Automatic update of dependency requests from 2.23.0 to 2.24.0
  Pipfile.lock
Labels: approved, bot

#284 Automatic update of dependency thoth-common from 0.13.8 to 0.13.13
  Pipfile.lock
Labels: approved, bot

#285 Automatic update of dependency pytest-asyncio from 0.12.0 to 0.14.0
  Pipfile.lock
Labels: approved, bot

#282 Add .thoth_last_analysis_id to .gitignore
  .gitignore
Labels: approved
