Repository thoth-station/python, pull requests merged in 2021-03, with the labels that each got.

#371 Version identifier should be always non-None value
  tests/test_pipfile.py
  thoth/python/package_version.py
  thoth/python/pipfile.py
  thoth/python/project.py
Labels: approved, size/S

#374 Add missing Kebechet templates
  .github/ISSUE_TEMPLATE/kebechet_info.md
  .github/ISSUE_TEMPLATE/kebechet_update.md
Labels: approved, size/S

#379 Optionally keep Thoth section when generating project
  .prow.yaml
  thoth/python/project.py
Labels: approved, size/XS

#378 add prow check with specific args
  .prow.yaml
Labels: lgtm, size/S

#386 Fix serialization of packages without version specifier
  thoth/python/pipfile.py
Labels: approved, size/XS
