Repository thoth-station/python, pull requests merged in 2021-02, with the labels that each got.

#335 Reformat setup.py to fix pre-commit complains
  setup.py
Labels: size/XS

#334 Introduce Thoth section in Pipfile
  .pre-commit-config.yaml
  tests/data/pipfiles/Pipfile_thoth
  tests/test_pipfile.py
  tests/test_provenance.py
  thoth/python/pipfile.py
  thoth/python/project.py
  thoth/python/source.py
Labels: approved, do-not-merge/hold, size/L

#341 Raise an error if editable installs are used
  tests/test_package_version.py
  thoth/python/package_version.py
Labels: approved, lgtm, size/S

#333 pep561 for type checking
  setup.py
  thoth/python/py.typed
Labels: approved, size/XS

#344 Register pytest markers
  MANIFEST.in
  pytest.ini
Labels: lgtm, size/XS

#343 Introduce supported version properties
  setup.py
  tests/test_package_version.py
  tests/test_project.py
  thoth/python/package_version.py
Labels: approved, size/L

#345 Fix signature to correctly describe return type
  thoth/python/project.py
Labels: approved, size/XS

#346 Fix signature and make sure factory for default is called
  thoth/python/project.py
Labels: approved, size/S

#349 Introduce disable index adjustment in Thoth's section in Pipfile
  tests/data/pipfiles/Pipfile_thoth
  tests/test_pipfile.py
  thoth/python/pipfile.py
Labels: approved, kind/feature, lgtm, sig/docs, size/M

#353 Add routines to support adding packages to Pipfile
  tests/test_pipfile.py
  thoth/python/exceptions.py
  thoth/python/package_version.py
  thoth/python/packages.py
  thoth/python/pipfile.py
  thoth/python/project.py
Labels: approved, size/L

#354 Optionally keep thoth specific configuration in Pipfile
  thoth/python/pipfile.py
  thoth/python/project.py
Labels: approved, size/S

#358 fridex Override entries in Thoth section if they do not meet type expected
  thoth/python/pipfile.py
Labels: approved, size/XS

#357 Fix serialization and loading of requirements files
  thoth/python/pipfile.py
  thoth/python/project.py
Labels: approved, size/XS

#363 pre-releases do not need to be always stated in Pipfile
  thoth/python/pipfile.py
Labels: approved, size/XS

#367 Copy dict before performing pop
  thoth/python/pipfile.py
Labels: approved, size/XS
