Repository thoth-station/python, pull requests merged in 2022-02, with the labels that each got.

#440 Strip any terminating slashes from index URL
  thoth/python/source.py
Labels: approved, size/XS

#439 Check lockfile hash on provenance checks
  tests/test_project.py
  thoth/python/project.py
Labels: approved, size/M

#442 Add myself to approvers
  OWNERS
Labels: approved, size/XS

#444 Add myself to maintainers
  .thoth.yaml
Labels: approved, size/XS

#452 Fix artifact obtaining on the Pulp instance
  thoth/python/aiosource.py
  thoth/python/source.py
Labels: approved, size/S

#455 Fix typo in error message
  thoth/python/project.py
Labels: approved, size/XS

#457 Fix constructing artifact url
  thoth/python/aiosource.py
  thoth/python/source.py
Labels: approved, size/XS

#463 Remove redeliver container image template
  .github/ISSUE_TEMPLATE/redeliver_container_image.md
Labels: approved, size/S, lgtm
