Repository thoth-station/python, pull requests merged in 2023-01, with the labels that each got.

#491 Convert to full pyproject.toml + Pipfile and get rid of requirements.txt
  MANIFEST.in
  pyproject.toml
  requirements.txt
  setup.py
Labels: approved, lgtm

#489 Limit packaging to <22
  Pipfile
  Pipfile.lock
Labels: approved, lgtm

#493 Remove pipfile-requirements from thoth.yaml and updated OWNERS
  .thoth.yaml
  OWNERS
Labels: size/XS

#486 Iterate over each artifacts instead of capturing in a list
  thoth/python/source.py
Labels: approved, size/M, lgtm
